apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: weatherforecast-steeltoe-csharp
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: weatherforecast-steeltoe-csharp
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: weatherforecast-steeltoe-csharp
    apps.tanzu.vmware.com/has-tests: true    
spec:
  env:
  - name: ASPNETCORE_ENVIRONMENT
    value: "Development" 
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/pivotal-asim-shaikh/weatherforecast-steeltoe-csharp
      ref:
        branch: main
  # params:
  #   - name: gitops_server_address
  #     value: https://github.com      
  #   - name: gitops_repository_owner
  #     value: pivotal-asim-shaikh
  #   - name: gitops_repository_name
  #     value: weatherforecast-deployment   
  #   - name: gitops_server_kind
  #     value: github
  #   - name: gitops_commit_branch
  #     value: ""
  #   - name: gitops_pull_request_title
  #     value: "Ready for review"
  #   - name: gitops_pull_request_body
  #     value: "Generated by supply chain"
    # - name: gitops_branch
    #   value: "main"
    # - name: gitops_commit_strategy
    #   value: pull_request
  # gitops:
    
  #   branch: "main"
  #   commit_strategy: pull_request
  #   pull_request:
  #     server_kind:  github
  #     commit_branch: ""
  #     pull_request_title: "Ready for review"
  #     pull_request_body:  generated by TAP supply chain
  
    
